### ISSUE TITLE
Support for es6

### ISSUE THREAD

**Issue by koenpunt** [jjeising/javascript-react.tmbundle#4]
It would be nice to have this bundle support es6. I've tried adding an es6 bundle and disabling regular javascript but without success. Any pointers maybe?

**Comment by jjeising** [comment]
ES 6 support has to be introduced in [textmate/javascript.tmbundle](https://github.com/textmate/javascript.tmbundle) (see also [#42](https://github.com/textmate/javascript.tmbundle/issues/42) and [#45](https://github.com/textmate/javascript.tmbundle/issues/45)). I've prepared a test file ([via](http://babeljs.io/docs/learn-es2015/)) but didn't had time to start yet. There are varying levels of complexity involved, keywords are relatively easy, lambdas and some keywords with advanced highlighting require adding more complex regular expressions.

It's still not finally decided how to integrate different flavors (ES6/7/…) there, but that shouldn't stop one from going forward with the implementation.

**Comment by infininight** [comment]
Support for many ES6 features has now been added to the JavaScript bundle.

**Comment by koenpunt** [comment]
Great, thanks!
