### ISSUE TITLE
Questionmark in content breaks syntax highlighting

### ISSUE THREAD

**Issue by koenpunt** [jjeising/javascript-react.tmbundle#5]
As you can see, after `Reset form fields?`, the highlighting is broken, when I remove the questionmark it works fine

![image](https://cloud.githubusercontent.com/assets/351038/13881398/14931624-ed21-11e5-8128-8344e3844c13.png)

**Comment by jjeising** [comment]
With the current implementation you'll have an ordinary JavaScript context between tags – the `?` starts a ternary operator here (you can see this when typing `?:`).

To fix this we should resolve text between tags to text like the HTML grammar does and only parse JavaScript inside curly braces. I have to check if it is possible to implement this.

As a simple workaround until then is wrapping the string in `{'…'}`, which is [also recommend elsewhere](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-no-literals.md):

```
<ActionDialog>
  {'Reset form fields?'}
</ActionDialog>
```

**Comment by koenpunt** [comment]
>  I have to check if it is possible to implement this.

Cool, in the meantime wrapping will do, thanks.

**Comment by jjeising** [comment]
@koenpunt I still haven't figured out how to nicely change the scope inside pairing tags, but the latest update here together with the updated Javascript bundle should fix this behavior.

**Comment by koenpunt** [comment]
> I still haven't figured out how to nicely change the scope inside pairing tags

You could ask on the TextMate mailing list, people on there tend to be very helpful: http://lists.macromates.com/listinfo/textmate

**Comment by jjeising** [comment]
Thanks to @infininight this should be fixed and work like expected. Now a question mark isn't even highlighted anymore (as JavaScript is not parsed between tags, except inside braces).
