### ISSUE TITLE
Is it possible to make it an injection grammar? 

### ISSUE THREAD

**Issue by koenpunt** [jjeising/javascript-react.tmbundle#7]
As the readme states

> Borrows heavily from textmate/html.tmbundle and textmate/javascript.tmbundle.

Couldn't this grammar be converted to an injection grammar? 

http://blog.macromates.com/2012/injection-grammars-project-variables/

**Comment by jjeising** [comment]
It might be a good idea to inject into `source.js`. We currently do something similar via `scopeName` (`source.js.react`). I'll try this when updating the grammar for #5.

**Comment by koenpunt** [comment]
Actually came back here because the official javascript bundle now has support for es6, which in turn caused the JSX not to render with HTML coloring anymore.. I'm not sure what you're "borrowing" from the html and javascript bundles, but it unfortunately doesn't work correct anymore... 😪

**Comment by jjeising** [comment]
Compatibility should be restored with 848d96d. It's now integrated as an injection grammar, thanks for the hint. I hope this works out.

**Comment by koenpunt** [comment]
Great, thanks!
